# Generated by Django 3.2.7 on 2021-10-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_useraccounts_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
