# Generated by Django 3.2.7 on 2021-09-30 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pack_no', models.CharField(max_length=50, editable=False, blank=True, unique=True)),
                ('total_weight', models.FloatField(default=0)),
                ('oversea_ship_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('foreign_domestic_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vn_domestic_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(default='', max_length=50)),
                ('to_start_ship_date', models.DateField(auto_now_add=True)),
                ('arrived_date', models.TimeField(auto_now_add=True)),
                ('memo', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('product_url', models.CharField(default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estimated_weight', models.FloatField(default=0)),
                ('measurement_weight', models.FloatField(default=0)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('ship_company', models.CharField(default='', max_length=50)),
                ('comfirm_notifed_fig', models.BooleanField(default=False)),
                ('memo_from_customer', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_no', models.CharField(blank=True, editable=False, max_length=50)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=12)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('total_product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_total_weight', models.FloatField(default=0)),
                ('estimated_ship_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estimated_total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fix_total_weight', models.FloatField(default=0)),
                ('fix_ship_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fix_total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('domestic_delivery_method', models.CharField(max_length=254)),
                ('payment_method', models.CharField(max_length=254)),
                ('memo', models.TextField(blank=True)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('delivery_time', models.TimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
