# Generated by Django 3.2.7 on 2021-10-03 03:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2021, 10, 3, 10, 27, 35, 463783))),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=12)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('REGISTER', 'Register Order'), ('CANCEL_BY_CUSTOMER', 'Cancel by Customer'), ('CANCEL_BY_EMPOLYEE', 'Cancel by Employee'), ('UNDER_SHIPPING', 'Under Shipping'), ('COMPLETED', 'Completed')], default='REGISTER', max_length=100)),
                ('total_product_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_total_weight', models.FloatField(default=0)),
                ('estimated_ship_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fix_total_weight', models.FloatField(default=0)),
                ('fix_ship_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fix_total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('domestic_delivery_method', models.CharField(choices=[('CUSTOMER_HOME', 'To delivery to customer home'), ('BRANCH', 'To delivery to company branch')], default='CUSTOMER_HOME', max_length=100)),
                ('payment_method', models.CharField(choices=[('BANK_ACCOUNT', 'To transfer bank account'), ('CASH', 'Pay by cash')], default='BANK_ACCOUNT', max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('delivery_time', models.TimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_weight', models.FloatField(default=0)),
                ('oversea_ship_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('foreign_domestic_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vn_domestic_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('REGISTER', 'Register Order'), ('CANCEL_BY_CUSTOMER', 'Cancel by Customer'), ('CANCEL_BY_EMPOLYEE', 'Cancel by Employee'), ('UNDER_SHIPPING', 'Under Shipping'), ('COMPLETED', 'Completed')], default='REGISTER', max_length=100)),
                ('to_start_ship_date', models.DateField(default=datetime.datetime(2021, 10, 3, 10, 27, 35, 464783))),
                ('arrived_date', models.TimeField(default=datetime.datetime(2021, 10, 3, 10, 27, 35, 464783))),
                ('memo', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('product_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_weight', models.FloatField(default=0)),
                ('measurement_weight', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('REGISTER', 'Register Order'), ('CANCEL_BY_CUSTOMER', 'Cancel by Customer'), ('CANCEL_BY_EMPOLYEE', 'Cancel by Employee'), ('UNDER_SHIPPING', 'Under Shipping'), ('COMPLETED', 'Completed')], default='REGISTER', max_length=100)),
                ('ship_company', models.CharField(default='', max_length=50)),
                ('comfirm_notifed_fig', models.BooleanField(default=False)),
                ('memo_from_customer', models.TextField(default='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_app.order')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase_app.pack')),
            ],
        ),
    ]
