# Generated by Django 3.2.7 on 2021-09-30 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0002_auto_20210930_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_no',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='purchase_app.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pack_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase_app.pack'),
        ),
        migrations.AlterField(
            model_name='order',
            name='domestic_delivery_method',
            field=models.CharField(choices=[('CUSTOMER_HOME', 'To delivery to customer home'), ('BRANCH', 'To delivery to company branch')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('REGISTER', 'Register Order'), ('CANCEL_BY_CUSTOMER', 'Cancel by Customer'), ('CANCEL_BY_EMPOLYEE', 'Cancel by Employee'), ('UNDER_SHIPPING', 'Under Shipping'), ('COMPLETED', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('REGISTER', 'Register Order'), ('CANCEL_BY_CUSTOMER', 'Cancel by Customer'), ('CANCEL_BY_EMPOLYEE', 'Cancel by Employee'), ('UNDER_SHIPPING', 'Under Shipping'), ('COMPLETED', 'Completed')], default='REGISTER', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('REGISTER', 'Register Order'), ('CANCEL_BY_CUSTOMER', 'Cancel by Customer'), ('CANCEL_BY_EMPOLYEE', 'Cancel by Employee'), ('UNDER_SHIPPING', 'Under Shipping'), ('COMPLETED', 'Completed')], default='REGISTER', max_length=100),
        ),
    ]
