# Generated by Django 3.2.7 on 2021-09-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0003_auto_20210930_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(),
        ),
    ]
