# Generated by Django 3.2.7 on 2021-10-03 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0003_auto_20211003_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 3, 11, 49, 15, 821801)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='arrived_date',
            field=models.TimeField(default=datetime.datetime(2021, 10, 3, 11, 49, 15, 825798)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='to_start_ship_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 3, 11, 49, 15, 825798)),
        ),
        migrations.AlterField(
            model_name='product',
            name='memo_from_customer',
            field=models.TextField(blank=True),
        ),
    ]
