# Generated by Django 3.2.7 on 2021-09-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0004_alter_product_product_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='order_no',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pack_no',
            new_name='pack_id',
        ),
    ]
