# Generated by Django 3.2.7 on 2021-09-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0005_auto_20210930_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='status',
            field=models.CharField(choices=[('REGISTER', 'Register Order'), ('CANCEL_BY_CUSTOMER', 'Cancel by Customer'), ('CANCEL_BY_EMPOLYEE', 'Cancel by Employee'), ('UNDER_SHIPPING', 'Under Shipping'), ('COMPLETED', 'Completed')], default='REGISTER', max_length=100),
        ),
    ]
