# Generated by Django 3.2.7 on 2021-09-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0006_alter_pack_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BANK_ACCOUNT', 'To transfer bank account'), ('CASH', 'Pay by cash')], max_length=100),
        ),
    ]
