# Generated by Django 3.2.7 on 2021-09-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0007_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pack_id',
            new_name='pack',
        ),
    ]
