# Generated by Django 3.2.7 on 2021-10-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0009_auto_20210930_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='domestic_delivery_method',
            field=models.CharField(choices=[('CUSTOMER_HOME', 'To delivery to customer home'), ('BRANCH', 'To delivery to company branch')], default='CUSTOMER_HOME', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('BANK_ACCOUNT', 'To transfer bank account'), ('CASH', 'Pay by cash')], default='BANK_ACCOUNT', max_length=100),
        ),
    ]
