# Generated by Django 3.2.7 on 2021-10-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0010_auto_20211001_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='memo',
            field=models.TextField(default='Memo form customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memo_from_customer',
            field=models.TextField(default='Memo form customer'),
        ),
    ]
