# Generated by Django 3.2.7 on 2021-10-13 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_app', '0019_auto_20211013_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 16, 0, 42, 660329)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='arrived_date',
            field=models.TimeField(default=datetime.datetime(2021, 10, 13, 16, 0, 42, 664328)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='to_start_ship_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 13, 16, 0, 42, 664328)),
        ),
    ]
